@echo off
REM ---------------------------------------------------------------
REM  ASCII-only on purpose; see the note in start.bat.
REM
REM  This deliberately does NOT call .venv\Scripts\activate.bat.
REM
REM  activate.bat is generated by Python's own `venv` module and it
REM  hard-codes the absolute path the venv was created at:
REM
REM      set "VIRTUAL_ENV=C:\...\<whatever>\.venv"
REM
REM  Rename or move any parent folder and that line points at a path
REM  that no longer exists. Editing it is pointless -- pip and venv
REM  regenerate it. So this script sets the same variables itself,
REM  derived from %~dp0 (the folder THIS file lives in), and keeps
REM  working wherever the project is moved to.
REM ---------------------------------------------------------------
setlocal
pushd "%~dp0"
title Roster - command line

if not exist ".venv\Scripts\python.exe" (
    echo [ERROR] Virtual environment not found. Run: python -m venv .venv
    popd
    pause
    exit /b 1
)

REM What activate.bat does, minus the hard-coded path.
set "VIRTUAL_ENV=%CD%\.venv"
set "PATH=%VIRTUAL_ENV%\Scripts;%PATH%"
set "PYTHONHOME="
set "PROMPT=(.venv) $P$G"

echo.
echo  Roster - virtual environment is active
echo  ---------------------------------------------------
echo   python main.py --help           list every command
echo   python main.py crawl -s sample  crawl the bundled sample
echo   python main.py crawl --url URL  crawl any page by URL
echo   python main.py export -f excel  export to Excel
echo   python main.py stats            database summary
echo   python main.py gui              open the window
echo.
echo  Tip: prefer "python -m pip" and "python -m pytest" over the
echo  bare "pip" / "pytest" commands. Those .exe launchers in
echo  .venv\Scripts embed an absolute path too and stop working if
echo  this folder is moved or renamed; "python -m" always works.
echo.

cmd /k
