#!/usr/bin/env bash
# Roster command line for Linux.
#
# This deliberately does NOT source .venv/bin/activate.
#
# `activate` is generated by Python's own venv module and hard-codes the
# absolute path the environment was created at, as a literal VIRTUAL_ENV
# assignment. Move or rename any parent folder and that line points at a
# path that no longer exists. Editing it is pointless -- pip and venv regenerate it. So
# this script exports the same variables itself, derived from the script's
# own location, and keeps working wherever the project ends up.
set -uo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$here"

if [ ! -x "$here/.venv/bin/python" ]; then
    echo "[ERROR] Not installed yet. Run ./install.sh in this same folder first."
    exit 1
fi

export VIRTUAL_ENV="$here/.venv"
export PATH="$VIRTUAL_ENV/bin:$PATH"
unset PYTHONHOME

# The mascots, from the one file every launcher on every platform shares.
printf "\n"
cat "$here/assets/pets.txt" 2>/dev/null

cat <<'EOF'

 Roster - virtual environment is active
 ---------------------------------------------------
  python main.py --help           list every command
  python main.py crawl -s sample  crawl the bundled sample
  python main.py crawl --url URL  crawl any page by URL
  python main.py export -f excel  export to Excel
  python main.py stats            database summary
  python main.py gui              open the window

 Tip: prefer "python -m pip" and "python -m pytest" over the bare
 "pip" / "pytest" commands. Those launchers in .venv/bin embed an
 absolute path too and stop working if this folder is moved or
 renamed; "python -m" always works.

EOF

exec "${SHELL:-/bin/bash}"
